# Atomic Pi — Intel Atom x5-Z8350 SBC by Digital Loggers
declare -g BOARD_NAME="Atomic Pi"
declare -g BOARD_VENDOR="Digital Loggers"
declare -g BOARDFAMILY="uefi-x86"
declare -g BOARD_MAINTAINER=""
declare -g INTRODUCED="2019"
declare -g KERNEL_TARGET="current,edge"
declare -g KERNEL_TEST_TARGET="current"
declare -g SERIALCON="ttyS0"
declare -g BOOT_LOGO=desktop
